language: node_js
os: osx
osx_image: xcode9.4

before_install:
  - npm update
  
node_js:
 - "stable"
branches:
 only:
 - master
before_script:
 - npm install -g ionic cordova
script:
 - ionic cordova build ios --release
 - npm t
 
notifications:
    slack: moolahfinancial:e6ZfUHKytRlTodjUX8Ck3N40
