//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolahFinancialBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class address
    {
        public int user_id { get; set; }
        public int address_id { get; set; }
        public string first_line { get; set; }
        public string second_line { get; set; }
        public string suite_number { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
        public bool is_deleted { get; set; }
        public bool is_primary_address { get; set; }
    
        public virtual user user { get; set; }
    }
}
