//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolahFinancialBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class holding
    {
        public int holding_id { get; set; }
        public string holding_name { get; set; }
        public decimal weight { get; set; }
        public decimal fees_per_year { get; set; }
        public int portfolio_id { get; set; }
    
        public virtual portfolio portfolio { get; set; }
    }
}
