//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolahFinancialBackend.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class news
    {
        public int portfolio_id { get; set; }
        public int news_id { get; set; }
        public string title { get; set; }
        public System.DateTime time_of_story { get; set; }
        public string author { get; set; }
        public string source { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
        public string article_url { get; set; }
        public string content { get; set; }
    
        public virtual portfolio portfolio { get; set; }
    }
}
