//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoolahFinancialBackend
{
    using System;
    using System.Collections.Generic;
    
    public partial class transaction
    {
        public int user_id { get; set; }
        public int portfolio_id { get; set; }
        public int transaction_id { get; set; }
        public System.DateTime investment_time { get; set; }
        public decimal investment_amount { get; set; }
        public bool is_sale { get; set; }
    
        public virtual portfolio portfolio { get; set; }
        public virtual user user { get; set; }
    }
}
